---
- name: Dump tackle 1.2 objects
  hosts: localhost
  gather_facts: false
  vars:
    tacke_url: 
    tackle_token: ""
  tasks:

  - name: Prepare data directory
    loop:
      - data
      # Dump contains files with list of records (dump list of objects)
      - data/dump
      - data/dump/application-inventory
      # Transformed data contains directories with list of files each representing single record (create one-by-one)
      - data/transformed
      - data/transformed/application-inventory
      - data/transformed/application-inventory/application
    file:
      path: "{{ item }}"
      state: directory
  
  - name: Dump tackle 1.2 resources
    loop:
      - application-inventory/application
    get_url:
      url: "{{ tacke_url }}/api/{{ item }}"
      dest: data/dump/{{ item }}
#      method: GET
      validate_certs: no
#      return_content: yes
#      body_format: json
      headers:
        Content-Type: "application/json"
        Authorization: "Bearer {{ tackle_token }}"
    register: res

  - name: Debug output
    debug: 
      var: res