---
- name: Dump tackle 1.2 objects
  hosts: localhost
  gather_facts: false
  vars:
    tacke_url: 
    tackle_token: ""
  tasks:

  - name: Prepare data directory
    loop:
      - mig-data-12
      - mig-data-12/application-inventory
    file:
      path: "{{ item }}"
      state: directory
  
  - name: Dump tackle 1.2 resources
    loop:
      - application-inventory/application
    get_url:
      url: "{{ tacke_url }}/api/{{ item }}"
      dest: mig-data-12/{{ item }}
#      method: GET
      validate_certs: no
#      return_content: yes
#      body_format: json
      headers:
        Content-Type: "application/json"
        Authorization: "Bearer {{ tackle_token }}"
    register: res

  - name: Debug output
    debug: 
      var: res