---
- name: Transform Tackle 1.2 objects to 2.0 objects
  hosts: localhost
  gather_facts: false
  tasks:

  - name: Iterate services to transform their objects - Applications
    loop: "{{ lookup('fileglob', 'mig-data-12/application-inventory/*', wantlist=True) }}"
    include_tasks: 2_transform_application.yaml
