---
- name: Dump tackle 1.2 objects
  hosts: localhost
  gather_facts: false
  tasks:

  - name: Prepare data directory
    loop:
      - mig-data-12
      - mig-data-12/application-inventory
    file:
      path: "{{ item }}"
      state: directory
  
  - name: Dump tackle 1.2 resources
    loop:
      - application-inventory/application
    uri:
      url: https://tackle-tackle.apps.mta01..../api/{{ item }}
      dest: mig-data-12/{{ item }}
      method: GET
      validate_certs: no
      return_content: yes
      body_format: json
      headers:
        Content-Type: "application/json"
        Authorization: "Bearer ..."
    register: res

  - name: Debug output
    debug: 
      var: res